### ISSUE TITLE
[Bug]: Route [login] not defined when access to an entity route

### ISSUE THREAD

**Issue by sambeauprak** [rupadana/filament-api-service#15]
### What happened?

I get the following error message : Route [login] not defined.

### How to reproduce the bug

When I access to a route: e.g: api/admin/customers/1 I get an error message which implies the route login not defined.

### Package Version

3.0

### PHP Version

8.2.12

### Laravel Version

10.35.0

### Which operating systems does with happen with?

Windows

**Comment by rupadana** [comment]
this package used `laravel-sanctum` enabled by default, when you did'nt adding `Authorization` header, you will directed to the login page. 

Because of you did'nt use Laravel Auth, Laravel did'nt found the login page. You need modify route name on `App\Http\Middleware\Authenticate` to `filament.admin.auth.login`

**Comment by sambeauprak** [comment]
Hi there, I did what you said and it's okay for the login page. So I added a Bearer Token through `Authorization` header, but it still redirect me to the login page.

I used Postman for that. Here's the request URL: https://topizyv2.dev/api/admin/customers
Here's the Authorization tab config:
![image](https://github.com/rupadana/filament-api-service/assets/17163273/269ee278-f830-441d-859c-b1d41363b29e)

**Comment by rupadana** [comment]
> Hi there, I did what you said and it's okay for the login page. So I added a Bearer Token through `Authorization` header, but it still redirect me to the login page.
> 
> I used Postman for that. Here's the request URL: https://topizyv2.dev/api/admin/customers Here's the Authorization tab config: ![image](https://private-user-images.githubusercontent.com/17163273/298034189-269ee278-f830-441d-859c-b1d41363b29e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Njg5ODQsIm5iZiI6MTcwNTY2ODY4NCwicGF0aCI6Ii8xNzE2MzI3My8yOTgwMzQxODktMjY5ZWUyNzgtZjgzMC00NDFkLTg1OWMtYjFkNDEzNjNiMjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyNTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNDU3MGI4NTQ5ZGI1ZWY3M2Q5NTg1ZDNhZjE4Mzk4NGI1ZDNjODRlNzI2OGZhMmI1Mjk3ZjUyZTJjYTJjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C81ldx4o_DprJ8P89limNMaRbnsDDP3pX1COOnLXKmM)

i think you didn't copy all the token showed cause its begin with "1|" the number is an ID of the token

**Comment by sambeauprak** [comment]
![image](https://github.com/rupadana/filament-api-service/assets/17163273/967e110e-95d8-44fa-9209-88ee9ad36587)
 I have this in my db. So as you said, my token should be `1|edf86e7c63001fd0e284b5ebb16b06a9107c725253050a62b069ba056f6dc1c5` ?

**Comment by rupadana** [comment]
> ![image](https://private-user-images.githubusercontent.com/17163273/298077359-967e110e-95d8-44fa-9209-88ee9ad36587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzcwMzksIm5iZiI6MTcwNTY3NjczOSwicGF0aCI6Ii8xNzE2MzI3My8yOTgwNzczNTktOTY3ZTExMGUtOTVkOC00NGZhLTkyMDktODhlZTlhZDM2NTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE1MDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NDkxYmFjZjAwZTgzNGIyNzY3NTJjM2RkNGQwOWJhNGM5MThlN2ZkYjA2ZGVkODQ3YTkxZDA3YmZhODQ5ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E6liwTftPVPnbWsYwGnE9nvDcuLlx38IpAoyGFhfVw4) I have this in my db. So as you said, my token should be `1|edf86e7c63001fd0e284b5ebb16b06a9107c725253050a62b069ba056f6dc1c5` ?
> 
> But I still get the login page.
> 
> ![image](https://private-user-images.githubusercontent.com/17163273/298079442-4ecb86a1-b9be-4b66-a5e0-39a97cefbd70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzcwMzksIm5iZiI6MTcwNTY3NjczOSwicGF0aCI6Ii8xNzE2MzI3My8yOTgwNzk0NDItNGVjYjg2YTEtYjliZS00YjY2LWE1ZTAtMzlhOTdjZWZiZDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE1MDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZDE5ZDI2ZTJlODA3MmQzODRkYTkwZjY5NGI3NWIzMmIwNTE3MzFmM2Q4ZGM2NzI5MGIyMzY1ZTQ2NWUyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6zanh2uI1ZH5S0IvkkeuRMIBB4MzO-f_D3Lcur6JFqU)

In your database it is encrypted token, you need to copy the token from notification after you created token. 


you need to back up it, because its only showed one time

**Comment by sambeauprak** [comment]
I got the same redirection to login page.

![image](https://github.com/rupadana/filament-api-service/assets/17163273/6efddfa3-44de-4b02-a1f8-d539420945b8)

What's wrong? Did I miss any settings?

**Comment by rupadana** [comment]
> I got the same redirection to login page.
> 
> ![image](https://private-user-images.githubusercontent.com/17163273/298116692-6efddfa3-44de-4b02-a1f8-d539420945b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODU0ODksIm5iZiI6MTcwNTY4NTE4OSwicGF0aCI6Ii8xNzE2MzI3My8yOTgxMTY2OTItNmVmZGRmYTMtNDRkZS00YjAyLWExZjgtZDUzOTQyMDk0NWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE3MjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZDVjY2IzZGNiMDE0NjI0OWFjOGQ1YTU5M2RlZGJiYzc5MmMwYWNhMjE3NWYzYWFkYWM3NmQ4Yzc5MWQxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3OULlgp-I4-fgLZtVz-n2uo-IIGrCD7Stjcz8VtIgK0)
> 
> What's wrong? Did I miss any settings?

Are you already checklist the abilities?

**Comment by sambeauprak** [comment]
![image](https://github.com/rupadana/filament-api-service/assets/17163273/9f5b5f8f-eb91-4ede-8c10-e0dfd4e2e954)

I have these abilities checked

**Comment by sambeauprak** [comment]
I just needed to refresh migrations my db. Thanks for your help

**Comment by krutsednar** [comment]
I have the same problem. Any solution for this?
