### ISSUE TITLE
[Question]: Hide token resource

### ISSUE THREAD

**Issue by KevinShianto** [rupadana/filament-api-service#17]
### What happened?

Hi, appreaciate your plugins, its helping me in a lot of ways, but I have a question.
Currently from the web perspective, I need to restrict some user from accessing the token page resources, how do I hide the token navigation?

### How to reproduce the bug

Login using any user

### Package Version

3.0

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by rupadana** [comment]
first thing i need to know, are you use `filament-shield`?

**Comment by KevinShianto** [comment]
> first thing i need to know, are you use `filament-shield`?

yes correct

**Comment by rupadana** [comment]
@KevinShianto now you can publish the resource by executing `artisan vendor:publish --tag=api-service-resource` and modify the resource
