### ISSUE TITLE
Allow non-admin users to generate API key to access their records

### ISSUE THREAD

**Issue by entrailz** [rupadana/filament-api-service#18]
### What happened?

Hi,

Is it possible/planned to allow individual users to generate API keys which allows them to access their records/data?

Thanks.

### How to reproduce the bug

N/A		

### Package Version

00

### PHP Version

00

### Laravel Version

00

**Comment by rupadana** [comment]
ill be add it to our milestone

**Comment by Odilbukh** [comment]
Yes, please do it. Becouse there is no role in users on some simple projects

**Comment by rupadana** [comment]
> Yes, please do it. Becouse there is no role in users on some simple projects

I think you have a different issue, in this issue is still using a role and permission. But the users can manage their own token. 
But as you mentioned, u project didnt use role.

am i right @entrailz ?

**Comment by rupadana** [comment]
did u mean, you need a public API or something else @Odilbukh ?

**Comment by Odilbukh** [comment]
@rupadana Yes, I mean public API. There is no users' role in my system. But I need API. Your package is very usefull in this case. But Token resource show and can create new token only super_admin role.

**Comment by rupadana** [comment]
> @rupadana Yes, I mean public API. There is no users' role in my system. But I need API. Your package is very usefull in this case. But Token resource show and can create new token only super_admin role. Now I dont know how to fix it

Yesterday we release version 3.0.7 and u can read [Readme](https://github.com/rupadana/filament-api-service?tab=readme-ov-file#token-resource)

**Comment by rupadana** [comment]
Thank you for your input. this feature is already now on version 3.0.9.
