### ISSUE TITLE
[Bug]: How publish config pckg?

### ISSUE THREAD

**Issue by passasooz** [rupadana/filament-api-service#24]
### What happened?

How can I publish the config file api-service.php?

### How to reproduce the bug

when you try to publish with php artisan vendor:publish --provider="Rupadna\ApiService\ApiServiceServi
ceProvider" --tag=config
it returns No publishable resources for tag [config]. 

### Package Version

2.0.0

### PHP Version

8.1.0

### Laravel Version

10.10

**Comment by rupadana** [comment]
u can publish it by execute this command "php artisan vendor:publish --tag=api-service-config"
