### ISSUE TITLE
Question: Resources under a 'company' panel?

### ISSUE THREAD

**Issue by sprklinginfo** [rupadana/filament-api-service#8]
### What happened?

Hi sorry to bother you. Most of my resources are under a 'Company' panel right now. After scanning the readme, I didn't see whether it would work for resources under a different panel, like 'company' or not. Are there setup required in this case? thanks. 

### How to reproduce the bug

just a question.

### Package Version

1.0.0

### PHP Version

8.1

### Laravel Version

10

**Comment by iamtomc** [comment]
I believe this package works mainly with your resources and models. So using your filament panel provider you can choose to put the resources under whichever panel you want. That just my thought from what I read on their instructions. I am yet to fully make use of the package.

**Comment by rupadana** [comment]
this package works mainly with your resources and models. u just need to execute `php artisan make:filament-api-service YourResource` and choose where the resource from.
